GET http://localhost:3067/show-movies

###
POST http://localhost:3067/create-movies
Content-Type: application/json

{
    "name": "Angry Birds O Filme",
    "genero": "animacao",
    "duracao": 96  ,
    "classificacao_etria": 12
}

###
DELETE http://localhost:3067/delete-movies/1

###
PUT http://localhost:3067/update-movies/10
Content-Type: application/json

{
    "name": "Homem-Aranha: Através do Aranhaverso",
    "genero": "animacao",
    "duracao": 140,
    "classificacao_etria": 14
}